### ISSUE TITLE
Duplicate subview in viewcontroller

### ISSUE THREAD

**Issue by ducnv2910** [iamshezad/SHPopup#2]
Hello, 

I got a problem that the subview was duplicated when the viewcontroller show up. Please check for me. Thank you very much.
![simulator screen shot - iphone 8 - 2018-07-31 at 10 59 42](https://user-images.githubusercontent.com/38209124/43436944-da70693a-94b0-11e8-9567-20836e65de2d.png)

**Comment by iamshezad** [comment]
@ducnv2910 Can you please share a sample project having the issue?

**Comment by ducnv2910** [comment]
it's large project so I will show the viewcontroller and method show popup.

**Comment by iamshezad** [comment]
@ducnv2910 ok

**Comment by iamshezad** [comment]
@ducnv2910 can I close this issue? because you haven't responded yet with the sample project.
